spring:
  application:
    name: crawler-manager
  profiles:
    active: local # default profile
  main:
    web-application-type: none

# logging config
logging:
  config: classpath:logback-spring.xml
  file: ${spring.application.name}  # logback-spring.xml 에서 .log 붙여준다.

---
spring:
  profiles: local
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://flio.iptime.org:3306/flio?useUnicode=true&characterEncoding=utf-8&connectionCollation=utf8_bin&characterSetResults=utf8&autoReconnectForPools=true&serverTimezone=Asia/Seoul&useSSL=false&zeroDateTimeBehavior=convertToNull&connectTimeout=3000&socketTimeout=30000&allowPublicKeyRetrieval=true
      username: flio
      password: flioflio
      initial-size: 1
      max-total: 3
      max-idle: 3
      min-idle: 3
      max-wait-millis: 3000
      validation-query: select 1 from dual
      test-on-borrow: true
      validationQueryTimeout: 10000
      default-auto-commit: true
      pool-prepared-statements: true
      max-open-prepared-statements: 1000


crawler:
  thread-num: 1
  max-delay: 500
  max-depth: 3
  history-path: /Users/flio/project/crawler-manager/history
  html-path: /Users/flio/project/crawler-manager/html
  image-path: /Users/flio/project/crawler-manager/image
  seed-info:
    temporary-view-url: http://localhost:8080/temporary/view
    temporary-save-url: http://localhost:8080/temporary/save
    search-url: https://post.naver.com/search/post.nhn?keyword=#keyword#&sortType=createDate.dsc&range=&term=all&navigationType=current
    search-url-pattern: https://post.naver.com/viewer/postView.nhn\?volumeNo=.*searchRank=.*$
    search-data-pattern: (?s)<!-- SE3-TEXT \{ -->.*?<!-- \} SE3-TEXT -->
    search-data-remove-front: <!-- SE3-TEXT \{ -->
    search-data-remove-back:  <!-- \} SE3-TEXT -->
    search-more-max: 30
    search-keyword-list:
      - 배음 하모닉스
      - THD
      - dolby atmos
      - Frequency Response
      - XLR TRS
      - 컴프레서 리미터
      - 오디오 인터페이스 dac
      - 믹싱 마스터링
      - 미디장비 추천
      - 폴리 사운드
      - 스튜디오 마이크
      - 보컬 레코딩 마이크
      - 진공관 트랜지스터 엠프
      - LP CD
      - 노이즈 캔슬링
      - 하이파이 입문
      - 홈레코딩 입문 스피커
      - 홈시어터 모션
      - 사운드 디자이너
      - 사운드 엔지니어
      - 하만카돈 스피커
      - 마샬 블루투스
      - 스피커
      - 마이크
      - 케이블
      - 앰프
      - 이어폰
      - 헤드폰
      - 음향장비
      - 소스기기
      - 악기
      - 음반